package annotation.generator;

import static util.Utils.PACKAGE_NAME;
import annotation.AutoGenerated;
import annotation.generator.interfaces.ScreenManagerGenerator;
import com.microsoft.playwright.Page;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;
import java.util.List;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.element.Modifier;
import lombok.SneakyThrows;
import util.Logger;
import util.Utils;

public record ScreenManagerGeneratorImpl(
    RoundEnvironment roundEnv,
    SpecsCreator specsCreator,
    ProcessingEnvironment processingEnvironment,
    Logger log) implements ScreenManagerGenerator {

    @Override
    public void generateScreenManager() {
        log.debug("Starting generateScreenManager");
        List<MethodSpec> methodSpecs = this.roundEnv.getElementsAnnotatedWith(AutoGenerated.class).stream()
            .filter(method -> !Utils.containsIgnoreCase(method.toString(), "widget"))
            .map(e -> specsCreator.generateScreenMethods(e, processingEnvironment))
            .toList();

        TypeSpec screenManagerSpec = TypeSpec.classBuilder("ScreenManager")
            .addModifiers(Modifier.PUBLIC)
            .addMethods(methodSpecs)
            .addMethod(constructorScreenManager())
            .addField(fieldScreenManager())
            .build();
        writeClass(screenManagerSpec);
        log.debug("Finished generateScreenManager");
    }

    private FieldSpec fieldScreenManager() {
        return FieldSpec.builder(TypeName.get(Page.class), "page")
            .addModifiers(Modifier.PRIVATE)
            .build();
    }

    private MethodSpec constructorScreenManager() {
        return MethodSpec.constructorBuilder()
            .addModifiers(Modifier.PUBLIC)
            .addParameter(Page.class, "page")
            .addStatement("this.page = page")
            .build();
    }

    @SneakyThrows
    private void writeClass(TypeSpec typeSpec) {
        log.debug("Writing class: " + typeSpec.name);
        JavaFile.builder(PACKAGE_NAME, typeSpec).build().writeTo(this.processingEnvironment.getFiler());
    }
}
